-- ============================================================================
--  KARTOTEKA-SYNC — instalacja / aktualizacja (schemat pod Edge Function)
--  Uruchom całość w Supabase: SQL Editor -> New query -> wklej -> Run.
--  Skrypt jest idempotentny — można go puścić wielokrotnie i na bazie, gdzie
--  część obiektów już istnieje.
--
--  Co zakłada:
--   1. `raporty.zaktualizowano` + trigger — znacznik ostatniej EDYCJI raportu.
--   2. `sync_wydania` — dziennik wydań eksportu (co, kiedy i z jakim skutkiem
--      poszło do Kartoteki).
--   3. `kartoteka_eksport()` — JEDNO zapytanie zwracające cały eksport jako
--      jsonb. To jest jedyne miejsce, w którym opisany jest zakres eksportu.
--
--  Zasada: cała logika analityczna siedzi po stronie ODBIORCY (Kartoteka).
--  Tutaj i w Edge Function nie ma żadnego liczenia, oceniania ani filtrowania
--  treści — patrz supabase/functions/kartoteka-sync/README.md.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. raporty.zaktualizowano — znacznik ostatniej edycji
--
-- Po co: raporty bywają EDYTOWANE po zapisaniu, a edycja nie zmienia ani
-- `numer`, ani `data_opracowania`. Bez tego znacznika odbiorca nie ma po czym
-- poznać, że wiersz jest inny niż ten, który już przetworzył — poprawiony
-- raport albo wchodzi drugi raz jako duplikat, albo nie wchodzi wcale.
-- Jedna kolumna i jeden trigger zdejmują cały ten problem.
--
-- Kolumna jest zakładana tylko wtedy, gdy jej nie ma; przy zakładaniu wiersze
-- sprzed migracji dostają znacznik równy `utworzono`, żeby archiwum nie
-- wyglądało na „zmienione dzisiaj". Blok musi wykonać się PRZED założeniem
-- triggera (inaczej backfill ustawiłby wszystkim now()).
-- ----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from information_schema.columns
     where table_schema = 'public'
       and table_name   = 'raporty'
       and column_name  = 'zaktualizowano'
  ) then
    alter table public.raporty
      add column zaktualizowano timestamptz not null default now();

    update public.raporty
       set zaktualizowano = utworzono
     where utworzono is not null;
  end if;
end $$;

create or replace function public.raporty_ustaw_zaktualizowano()
returns trigger
language plpgsql
as $$
begin
  new.zaktualizowano := now();
  return new;
end;
$$;

drop trigger if exists raporty_zaktualizowano on public.raporty;
create trigger raporty_zaktualizowano
  before update on public.raporty
  for each row execute function public.raporty_ustaw_zaktualizowano();


-- ----------------------------------------------------------------------------
-- 2. sync_wydania — dziennik wydań eksportu
--
-- Jeden wiersz = jedno WYDANIE (nie jedna wiadomość). Wydanie podzielone na
-- części to nadal jeden wiersz — części różnią się tylko polem `czesc` w
-- kopercie maila.
--
-- `hash`  — sha256 tekstu JSON payloadu; służy do pominięcia wysyłki, gdy nic
--           się nie zmieniło.
-- `blad`  — NULL przy wysyłce udanej, treść błędu przy nieudanej. Edge Function
--           porównuje hash z ostatnim wierszem, w którym `blad is null` —
--           dzięki temu nieudana wysyłka nie „zatrzaskuje" wydania: kolejny
--           przebieg spróbuje jeszcze raz.
-- ----------------------------------------------------------------------------
create table if not exists public.sync_wydania (
  numer        integer generated by default as identity primary key,
  wygenerowano timestamptz not null default now(),
  hash         text not null,
  payload      jsonb,
  wyslano_do   text,
  blad         text
);

create index if not exists sync_wydania_wygenerowano_idx
  on public.sync_wydania (wygenerowano desc);

alter table public.sync_wydania enable row level security;

-- Celowo BEZ żadnej polityki: tabelę widzi wyłącznie `service_role` (Edge
-- Function) oraz właściciel bazy przez SQL Editor. Ani anon, ani zalogowana
-- aplikacja front-end nie mają tu wstępu — payload zawiera całą bazę raportową.


-- ----------------------------------------------------------------------------
-- 3. kartoteka_eksport() — całość eksportu jednym zapytaniem
--
-- To jest DOKŁADNIE to zapytanie, które właściciel uruchomił ręcznie
-- 31.07.2026 i na którego wyniku zaprojektowano odbiorcę. Nie zmieniaj go bez
-- uzgodnienia po stronie Kartoteki.
--
-- Wyłączone są WYŁĄCZNIE:
--   `zdjecia`, `grafika_url`, `harmonogram_urls` — setki URL-i do plików,
--   `token`                                     — nie wygasa, otwiera raport
--                                                 bez logowania.
-- Wszystko inne idzie w całości: pełny `harmonogram`, kwoty, HTML w polach
-- tekstowych i kolumny, które dopiero powstaną — `to_jsonb(...)` zabierze je
-- automatycznie, bez zmiany tej funkcji.
--
-- Okno `rn <= 1` (najnowszy raport na inwestycję) to jedyne ograniczenie ILOŚCI.
-- Historia się nie zmienia, a odbiorca ma ją u siebie. Żadne pole nie jest
-- oceniane — to nie jest selekcja treści.
--
-- Okno było pierwotnie `rn <= 2`; zwężone do jednego raportu decyzją
-- właściciela. Gdyby odbiorca kiedyś potrzebował poprzedniego raportu do
-- porównania, zmiana wraca tu i tylko tu — jedna cyfra, bez ruszania funkcji.
--
-- Uwaga dla odbiorcy: `to_jsonb(r)` jest liczone na podzapytaniu z funkcją
-- okna, więc każdy wiersz `raporty` niesie dodatkowe pole `rn` (przy tym oknie
-- zawsze `1`). Tak wyglądał ręczny eksport i tak zostaje.
--
-- SECURITY DEFINER: funkcja czyta wszystkie wiersze niezależnie od RLS.
-- Wykonanie ma wyłącznie `service_role` — nadanie tego prawa komukolwiek
-- innemu oznacza wydanie całej bazy raportowej.
-- ----------------------------------------------------------------------------
create or replace function public.kartoteka_eksport()
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select jsonb_build_object(
    'zakresy',      (select coalesce(jsonb_agg(to_jsonb(z)), '[]'::jsonb) from zakresy z),
    'uzytkownicy',  (select coalesce(jsonb_agg(to_jsonb(u)), '[]'::jsonb) from uzytkownicy u),
    'projekty',     (select coalesce(jsonb_agg(to_jsonb(p)), '[]'::jsonb) from projekty p),
    'przypisania',  (select coalesce(jsonb_agg(to_jsonb(a)), '[]'::jsonb) from przypisania a),
    'raporty',      (select coalesce(jsonb_agg(to_jsonb(r) - 'zdjecia' - 'grafika_url' - 'harmonogram_urls'), '[]'::jsonb)
                       from (select *, row_number() over (partition by projekt_id order by numer desc) as rn
                               from raporty) r
                      where r.rn <= 1),
    'udostepnienia',(select coalesce(jsonb_agg(to_jsonb(s) - 'token'), '[]'::jsonb) from udostepnienia s)
  );
$$;

revoke all on function public.kartoteka_eksport() from public;
revoke all on function public.kartoteka_eksport() from anon, authenticated;
grant execute on function public.kartoteka_eksport() to service_role;
