-- ============================================================================
--  KEEP-ALIVE — zapobieganie auto-pauzie darmowego projektu Supabase
--  Uruchom całość w Supabase: SQL Editor -> New query -> wklej -> Run.
--
--  Problem: darmowy projekt Supabase jest automatycznie pauzowany po 7 dniach
--  bez żadnego requestu do API. Rozwiązanie: cykliczny (2x w tygodniu) GET
--  z GitHub Actions na tę tabelę utrzymuje projekt „przy życiu".
--
--  Zasada bezpieczeństwa: rola `anon` ma WYŁĄCZNIE odczyt (SELECT) tej jednej,
--  pustej znaczeniowo tabeli. Żadnych innych uprawnień — brak INSERT/UPDATE/
--  DELETE i brak dostępu do jakichkolwiek danych aplikacji.
--
--  Skrypt jest idempotentny — można go bezpiecznie puścić wielokrotnie:
--   - CREATE TABLE IF NOT EXISTS (nie nadpisze istniejącej tabeli),
--   - DROP POLICY IF EXISTS przed CREATE POLICY (odświeży politykę),
--   - INSERT tylko gdy tabela jest pusta (nie mnoży wierszy).
-- ============================================================================

create table if not exists public.keep_alive (
  id        bigint generated by default as identity primary key,
  pinged_at timestamptz default now()
);

-- Jeden wiersz „zaczepienia" — INSERT tylko gdy tabela jest jeszcze pusta.
insert into public.keep_alive (pinged_at)
select now()
where not exists (select 1 from public.keep_alive);

alter table public.keep_alive enable row level security;

-- Anonim: WYŁĄCZNIE odczyt. Żadnych innych polityk (brak insert/update/delete).
drop policy if exists keep_alive_select on public.keep_alive;
create policy keep_alive_select on public.keep_alive
  for select to anon using (true);
